pokedexdjango/urls.py
from django.urls import path
from . import views

app_name = 'pokedexdjango'
urlpatterns = [
    path('', views.pokemon_list, name='home'),
    path('pokemon/list', views.pokemon_list, name='pokemon_list'),
    path('pokemon/details/<int:id>/', views.pokemon_details, name='pokemon_details'),
    path('pokemon/remove-favourite/<int:id>/', views.remove_fav_pokemon, name='remove_fav_pokemon'),
    path('pokemon/add-favourite/<int:id>/', views.add_fav_pokemon, name='add_fav_pokemon'),
    path('user_info/', views.user_info, name='user_info'),
    path('top_10/', views.top_10, name='top_10'),
    path('top_10_pokemons/', views.top_10_pokemons, name='top_10_pokemons'),
    path('top_10_not_legendary/', views.top_10_not_legendary, name='top_10_not_legendary'),
    path('top_10_water/', views.top_10_water, name='top_10_water'),
    path('top_10_attack/', views.top_10_attack, name='top_10_attack'),
    path('top_10_defence/', views.top_10_defence, name='top_10_defence'),
    path('top_10_hp/', views.top_10_hp, name='top_10_hp'),
    path("register/", views.register, name="register"),
    path("pokemon/list/favourite/", views.favourite_pokemons, name="favourite_pokemons"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
    # path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('', include('pokedexdjango.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path(
        'change_password/',
        auth_views.PasswordChangeView.as_view(
            template_name='registration/change_password.html',
            success_url='/'
        ),
        name='change_password'
    ),
    path(
        'reset_password/',
        auth_views.PasswordResetView.as_view(
            template_name='registration/reset_password.html',
            success_url='/'
        ),
        name='reset_password'
    ),

]

pokedexdjango/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Pokemon(models.Model):
    # id = models.PositiveIntegerField()
    poke_id = models.PositiveIntegerField()
    name = models.CharField(max_length=150)
    type_1 = models.CharField(max_length=150)
    type_2 = models.CharField(max_length=150)
    total = models.IntegerField()
    hp = models.IntegerField()
    attack = models.IntegerField()
    defence = models.IntegerField()
    sp_attack = models.IntegerField()
    sp_defence = models.IntegerField()
    speed = models.IntegerField()
    generation = models.SmallIntegerField()
    legendary = models.CharField(max_length=150)

#

    def __str__(self):
        return self.name

class CustomUser(AbstractUser):
    class Meta:
        db_table = 'auth_user'
    legendary = models.CharField(max_length=150, null=True, blank=True)
    favourite_pokemon = models.ManyToManyField(Pokemon)





pokedexdjango/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from pokedexdjango.models import CustomUser


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = CustomUser
        fields = ["username", "email", "password1", "password2", "first_name", "last_name", "legendary"]

pokedexdjango/views.py
from django.shortcuts import render
from django.db.models import Q
from .models import Pokemon
from django.shortcuts import redirect
from django.contrib import messages
from .forms import RegisterForm
from django.core.files.storage import default_storage
from django.conf import settings
from django.template.defaulttags import register


@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)


def __validate_search_form(request) -> bool:
    poke_id_param = request.GET.get('poke_id', '')
    name_param = request.GET.get('name', '')
    type_param = request.GET.get('type', '')
    total_param = request.GET.get('total', '')
    hp_param = request.GET.get('hp', '')
    attack_param = request.GET.get('attack', '')
    defence_param = request.GET.get('defence', '')
    sp_attack_param = request.GET.get('sp_attack', '')
    sp_defence_param = request.GET.get('sp_defence', '')
    speed_param = request.GET.get('speed', '')
    generation_param = request.GET.get('generation', '')

    is_valid = True

    if type_param != '' and not type_param.isdigit():
        messages.add_message(request, messages.ERROR, 'Type must be a number.')
        is_valid = False

    if name_param != '' and not all(x.isalpha() or x.isspace() for x in name_param):
        messages.add_message(request, messages.ERROR, 'Name must consist of letters.')
        is_valid = False

    if poke_id_param != '' and not poke_id_param.isdigit():
        messages.add_message(request, messages.ERROR, 'Poke id must be a number.')
        is_valid = False

    if total_param != '' and not total_param.isdigit():
        messages.add_message(request, messages.ERROR, 'Total must be a number.')
        is_valid = False

    if hp_param != '' and not hp_param.isdigit():
        messages.add_message(request, messages.ERROR, 'Hp must be a number.')
        is_valid = False

    if attack_param != '' and not attack_param.isdigit():
        messages.add_message(request, messages.ERROR, 'Attack must be a number.')
        is_valid = False

    if defence_param != '' and not defence_param.isdigit():
        messages.add_message(request, messages.ERROR, 'Defence must be a number.')
        is_valid = False

    if sp_attack_param != '' and not sp_attack_param.isdigit():
        messages.add_message(request, messages.ERROR, 'Sp attack must be a number.')
        is_valid = False

    if sp_defence_param != '' and not sp_defence_param.isdigit():
        messages.add_message(request, messages.ERROR, 'Sp defence must be a number.')
        is_valid = False

    if speed_param != '' and not speed_param.isdigit():
        messages.add_message(request, messages.ERROR, 'Speed must be a number.')
        is_valid = False

    if generation_param != '' and not generation_param.isdigit():
        messages.add_message(request, messages.ERROR, 'Generation must be a number.')
        is_valid = False

    return is_valid


def pokemon_details(request, id):
    title = 'Pokemon Details'

    poke_id_param = id
    pokemon_details = Pokemon.objects.get(id=poke_id_param)
    current_user = request.user
    is_favourite = False

    if current_user.is_authenticated:
        my_fav_pokemon = current_user.favourite_pokemon.filter(id=poke_id_param).first()
        if my_fav_pokemon != None:
            is_favourite = True

    return render(request,
                  'pokedexdjango/pokemon_details.html',
                  {
                      'title': title,
                      'pokemon': pokemon_details,
                      'is_favourite': is_favourite
                  })

def add_fav_pokemon(request, id):

    poke_id_param = id
    pokemon_details = Pokemon.objects.get(id=poke_id_param)
    current_user = request.user

    if current_user.is_authenticated == False:
        messages.add_message(request, messages.ERROR, 'You are not authenticated, please log in.')
        return redirect("pokedexdjango:pokemon_details", id=poke_id_param)

    my_fav_pokemon = current_user.favourite_pokemon.filter(id=poke_id_param).first()
    if my_fav_pokemon != None:
        messages.add_message(request, messages.ERROR, 'This pokemon is already on your favourite pokemon list.')
        return redirect("pokedexdjango:pokemon_details", id=poke_id_param)

    current_user.favourite_pokemon.add(pokemon_details)
    current_user.save()
    return redirect("pokedexdjango:pokemon_details", id=poke_id_param)

def remove_fav_pokemon(request, id):
    poke_id_param = id
    pokemon_details = Pokemon.objects.get(id=poke_id_param)
    current_user = request.user

    if current_user.is_authenticated == False:
        messages.add_message(request, messages.ERROR, 'You are not authenticated, please log in.')
        return redirect("pokedexdjango:pokemon_details", id=poke_id_param)

    my_fav_pokemon = current_user.favourite_pokemon.filter(id=poke_id_param).first()
    if my_fav_pokemon == None:
        messages.add_message(request, messages.ERROR, 'This pokemon is not on your favourite pokemon list.')
        return redirect("pokedexdjango:pokemon_details", id=poke_id_param)

    current_user.favourite_pokemon.remove(pokemon_details)
    current_user.save()
    return redirect("pokedexdjango:pokemon_details", id=poke_id_param)

def pokemon_list(request):


    title = 'Pokemon list'

    poke_id_param = request.GET.get('poke_id', '')
    name_param = request.GET.get('name', '')
    type_param = request.GET.get('type', '')
    total_param = request.GET.get('total', '')
    hp_param = request.GET.get('hp', '')
    attack_param = request.GET.get('attack', '')
    defence_param = request.GET.get('defence', '')
    sp_attack_param = request.GET.get('sp_attack', '')
    sp_defence_param = request.GET.get('sp_defence', '')
    speed_param = request.GET.get('speed', '')
    generation_param = request.GET.get('generation', '')
    sort_by_param = request.GET.get('sort_by', '')
    sort_direction_param = request.GET.get('sort_direction', '')

    pokemon_list = Pokemon.objects.all()

    is_valid = __validate_search_form(request)

    if not is_valid:
        return redirect('pokedexdjango:pokemon_list')

    if type_param != '':
        pokemon_list = pokemon_list.filter(Q(type_1__contains=type_param) | Q(type_2__contains=type_param))

    if name_param != '':
        pokemon_list = pokemon_list.filter(name__contains=name_param)

    if poke_id_param != '':
        pokemon_list = pokemon_list.filter(poke_id=poke_id_param)

    if total_param != '':
        pokemon_list = pokemon_list.filter(total=total_param)

    if hp_param != '':
        pokemon_list = pokemon_list.filter(hp=hp_param)

    if attack_param != '':
        pokemon_list = pokemon_list.filter(attack=attack_param)

    if defence_param != '':
        pokemon_list = pokemon_list.filter(defence=defence_param)

    if sp_attack_param != '':
        pokemon_list = pokemon_list.filter(sp_attack=sp_attack_param)

    if sp_defence_param != '':
        pokemon_list = pokemon_list.filter(sp_defence=sp_defence_param)

    if speed_param != '':
        pokemon_list = pokemon_list.filter(speed=speed_param)

    if generation_param != '':
        pokemon_list = pokemon_list.filter(generation=generation_param)

    if sort_by_param != '':
        sort_by_desc = sort_by_param
        if sort_direction_param == 'desc':
            sort_by_desc = '-' + sort_by_param
        pokemon_list = pokemon_list.order_by(sort_by_desc, 'poke_id')
    else:
        pokemon_list = pokemon_list.order_by('poke_id')

    pokemon_images = __get_pokemon_images(pokemon_list)

    pokemon_favourites = __get_pokemon_favourties(pokemon_list, request)

    # print(pokemon_favourites)

    return render(request,
                  'pokedexdjango/pokemon_list.html',
                  {
                      'title': title,
                      'pokemon_list': pokemon_list,
                      'pokemon_images': pokemon_images,
                      'pokemon_favourites': pokemon_favourites,
                      'form_action': request.path,
                      'poke_id_param': poke_id_param,
                      'name_param': name_param,
                      'type_param': type_param,
                      'total_param': total_param,
                      'hp_param': hp_param,
                      'attack_param': attack_param,
                      'defence_param': defence_param,
                      'sp_attack_param': sp_attack_param,
                      'sp_defence_param': sp_defence_param,
                      'speed_param': speed_param,
                      'generation_param': generation_param,
                      'sort_by_param': sort_by_param,
                      'sort_direction_param': sort_direction_param
                  })


def __get_pokemon_favourties(pokemon_list, request) -> dict:
    current_user = request.user
    pokemon_favourites = dict()

    for pokemon in pokemon_list:
        my_fav_pokemon = current_user.favourite_pokemon.filter(id=pokemon.id).first()
        pokemon_favourites[pokemon.id] = my_fav_pokemon is not None

    return pokemon_favourites

def __get_pokemon_images(pokemon_list) -> dict:
    pokemon_images = dict()

    for x in pokemon_list:
        pokemon_image_path = str(settings.BASE_DIR) + '/static/images/' + str(x.poke_id) + '.jpg'
        exist = default_storage.exists(pokemon_image_path)
        pokemon_images[x.poke_id] = exist

    return pokemon_images


def favourite_pokemons(request):
    current_user = request.user
    pokemon_list = current_user.favourite_pokemon.all()

    pokemon_images = __get_pokemon_images(pokemon_list)
    pokemon_favourites = __get_pokemon_favourties(pokemon_list, request)

    print(favourite_pokemons)

pokedexdjango/templates/pokedexdjango/favourite_pokemons.html
{% extends 'base.html' %}

{% block content %}
<h1>Favourite pokemons</h1>
{% include "partials/pokemon_table.html" with pokemon_list=pokemon_list pokemon_images=pokemon_images pokemon_favourites=pokemon_favourites %}
{% endblock %}

pokedexdjango/templates/pokedexdjango/pokemon_details.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<h1 class="text-center">{{pokemon.name}}</h1>
<br>
<div class="row">
    <div class="justify-content-center d-flex">
        <img src="/static/images/{{ pokemon.poke_id }}.jpg" width="150" height="150" class="img-responsive">
    </div>
</div>

{% if user.is_authenticated %}
{% if is_favourite == False %}
<div class="row p-2">
    <div class="justify-content-center d-flex">
        <a href="{% url 'pokedexdjango:add_fav_pokemon' id=pokemon.id %}" class="btn btn-success">Add to favourite</a>
<!--        <form method="post" action="{% url 'pokedexdjango:add_fav_pokemon' id=pokemon.id %}">-->
<!--            {% csrf_token %}-->
<!--            <button type="submit" class="btn btn-success">Add to favourite</button>-->
<!--        </form>-->
    </div>
</div>
{% else %}
<div class="row p-2">
    <div class="justify-content-center d-flex">
        <a href="{% url 'pokedexdjango:remove_fav_pokemon' id=pokemon.id %}" class="btn btn-danger">Remove from favourite</a>
<!--        <form method="post" action="{% url 'pokedexdjango:remove_fav_pokemon' id=pokemon.id %}">-->
<!--            {% csrf_token %}-->
<!--            <button type="submit" class="btn btn-danger">Remove from favourite</button>-->
<!--        </form>-->
    </div>
</div>
{% endif %}
{% endif %}

<div class="table-responsive-sm row justify-content-center">
    <table class="table table-bordered center" style="width:50%">
        <thead>
        <tr>
            <th scope="row">No</th>
            <td scope="row">{{pokemon.id}}</td>
        </tr>
        <tr>
            <th scope="row">Poke id</th>
            <td scope="row">{{pokemon.poke_id}}</td>
        </tr>
        <tr>
            <th scope="row">Name</th>
            <td scope="row">{{pokemon.name}}</td>
        </tr>
        <tr>
            <th scope="row">Type 1</th>
            <td scope="row">{{pokemon.type_1}}</td>
        </tr>
        <tr>
            <th scope="row">Type 2</th>
            <td scope="row">{{pokemon.type_2}}</td>
        </tr>
        <tr>
            <th scope="row">Total</th>
            <td scope="row">{{pokemon.total}}</td>
        </tr>
        <tr>
            <th scope="row">Hp</th>
            <td scope="row">{{pokemon.hp}}</td>
        </tr>
        <tr>
            <th scope="row">Attack</th>
            <td scope="row">{{pokemon.attack}}</td>
        </tr>
        <tr>
            <th scope="row">Defence</th>
            <td scope="row">{{pokemon.defence}}</td>
        </tr>
        <tr>
            <th scope="row">Sp attack</th>
            <td scope="row">{{pokemon.sp_attack}}</td>
        </tr>
        <tr>
            <th scope="row">Sp defence</th>
            <td scope="row">{{pokemon.sp_defence}}</td>
        </tr>
        <tr>
            <th scope="row">Speed</th>
            <td scope="row">{{pokemon.name}}</td>
        </tr>
        <tr>
            <th scope="row">Generation</th>
            <td scope="row">{{pokemon.generation}}</td>
        </tr>
        <tr>
            <th scope="row">Legendary</th>
            <td scope="row">{{pokemon.legendary}}</td>
        </tr>
        </thead>
    </table>
</div>

{% endblock  %}

pokedexdjango/templates/pokedexdjango/pokemon_list.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<script>
    $(document).ready(function() {
        $(".toast").toast('show');
    });
</script>
<h1 class="pokemon_list_header">Pokemon list</h1>
<div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
  <div class="toast-header">
    <strong class="me-auto">Admin</strong>
    <small class="text-muted">2 secs ago</small>
    <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
  </div>
  <div class="toast-body">
    Hi, thanks for visiting my page!
  </div>
</div>
<form action="{{ form_action }}" method="GET">
    <div class="row g-3 pb-1">
        <div class="col-auto">
            <input type="number"  min="1" max="1000" step="1" id="poke_id" name="poke_id" placeholder="poke id" class="form-control" value="{{ poke_id_param }}">
        </div>
        <div class="col-auto">
<!--            <label for="name" class="form-label">Name:</label>-->
            <input type="text" id="name" name="name" placeholder="pokemon name" class="form-control" value="{{ name_param }}">
        </div>
        <div class="col-auto">
<!--            <label for="type" class="form-label">Type:</label>-->
            <input type="text" id="type" name="type" placeholder="pokemon type" class="form-control" value="{{ type_param }}">
        </div>
    </div>
    <div class="row g-3 pb-1">
        <div class="col-auto">
            <input type="number"  min="1" max="1000" step="1" id="total" name="total" placeholder="total" class="form-control" value="{{ total_param }}">
        </div>
        <div class="col-auto">
            <input type="number" min="1" max="255" step="1" id="hp" name="hp" placeholder="pokemon hp" class="form-control" value="{{ hp_param }}">
        </div>
        <div class="col-auto">
            <input type="number" min="1" max="255" step="1" id="attack" name="attack" placeholder="attack" class="form-control" value="{{ attack_param }}">
        </div>
    </div>
    <div class="row g-3 pb-1">
        <div class="col-auto">
            <input type="number" min="1" max="255" step="1" id="defence" name="defence" placeholder="defence" class="form-control" value="{{ defence_param }}">
        </div>
        <div class="col-auto">
            <input type="number" min="1" max="255" step="1" id="sp_attack" name="sp_attack" placeholder="sp attack" class="form-control" value="{{ sp_attack_param }}">
        </div>
        <div class="col-auto">
            <input type="number" min="1" max="255" step="1" id="sp_defence" name="sp_defence" placeholder="sp defence" class="form-control" value="{{ sp_defence_param }}">
        </div>
    </div>
    <div class="row g-3 pb-1">
        <div class="col-auto">
            <input type="number" min="1" max="255" step="1" id="speed" name="speed" placeholder="speed" class="form-control" value="{{ speed_param }}">
        </div>
        <div class="col-auto">
            <input type="number" min="1" max="6" step="1" id="generation" name="generation" placeholder="generation" class="form-control" value="{{ generation_param }}">
        </div>
    </div>
     <div class="row g-3 pb-1">
        <div class="col-auto">
            <select id="sort_by" name="sort_by" class="form-control">
                <option value="">Sort by</option>
                <option value="poke_id" {% if sort_by_param == 'poke_id' %}selected{% endif %}>Poke id</option>
                <option value="name" {% if sort_by_param == 'name'%}selected{% endif %}>Name</option>
                <option value="type_1" {% if sort_by_param == 'type_1'%}selected{% endif %}>Type 1</option>
                <option value="type_2" {% if sort_by_param == 'type_2'%}selected{% endif %}>Type 2</option>
                <option value="total" {% if sort_by_param == 'total'%}selected{% endif %}>Total</option>
                <option value="hp" {% if sort_by_param == 'hp'%}selected{% endif %}>Hp</option>
                <option value="attack" {% if sort_by_param == 'attack'%}selected{% endif %}>Attack</option>
                <option value="defence" {% if sort_by_param == 'defence'%}selected{% endif %}>Defence</option>
                <option value="sp_attack" {% if sort_by_param == 'sp_attack'%}selected{% endif %}>Sp attack</option>
                <option value="sp_defence" {% if sort_by_param == 'sp_defence'%}selected{% endif %}>Sp defence</option>
                <option value="speed" {% if sort_by_param == 'speed'%}selected{% endif %}>Speed</option>
                <option value="generation" {% if sort_by_param == 'generation'%}selected{% endif %}>Generation</option>
            </select>
        </div>
         <div class="col-auto">
            <select id="sort_direction" name="sort_direction" class="form-control">
                <option value="">Sort direction</option>
                <option value="asc" {% if sort_direction_param == 'asc'%}selected{% endif %}>Ascending</option>
                <option value="desc" {% if sort_direction_param == 'desc'%}selected{% endif %}>Descending</option>
            </select>
        </div>
    </div>
    <div class="row g-3 pb-1">
        <div class="col-auto">
            <button type="submit" class="btn btn-success">Search</button>
        </div>
    </div>



</form>
<br>
{% include "partials/pokemon_table.html" with pokemon_list=pokemon_list pokemon_images=pokemon_images pokemon_favourites=pokemon_favourites %}
{% endblock  %}

pokedexdjango/templates/pokedexdjango/top_10.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<style>
h1 {
  text-align: center;
}
</style>
<h1>TOP 10</h1>

<ul>
    <li>
        <a href="{% url 'pokedexdjango:top_10_pokemons' %}">TOP 10 Pokemon</a>
    </li>
    <li>
        <a href="{% url 'pokedexdjango:top_10_not_legendary' %}">TOP 10 Pokemon that are not legendary</a>
    </li>
    <li>
        <a href="{% url 'pokedexdjango:top_10_water' %}">TOP 10 water Pokemon</a>
    </li>
    <li>
        <a href="{% url 'pokedexdjango:top_10_hp' %}">TOP 10 Pokemon with the biggest health</a>
    </li>
    <li>
        <a href="{% url 'pokedexdjango:top_10_attack' %}">TOP 10 Pokemon with the biggest attack</a>
    </li>
    <li>
        <a href="{% url 'pokedexdjango:top_10_defence' %}">TOP 10 Pokemon with the biggest defence</a>
    </li>
</ul>
{% endblock  %}

pokedexdjango/templates/pokedexdjango/top_10_attack.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<style>
h1 {
  text-align: center;
}
</style>
<h1 class="pokemon_list_header">
    TOP 10 Pokemon with the best attack
</h1>
{% include "partials/pokemon_table.html" with pokemon_list=pokemon_list pokemon_images=pokemon_images pokemon_favourites=pokemon_favourites %}
{% endblock  %}

pokedexdjango/templates/pokedexdjango/top_10_defence.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<style>
h1 {
  text-align: center;
}
</style>
<h1 class="pokemon_list_header">
    TOP 10 Pokemons with the best defence
</h1>
{% include "partials/pokemon_table.html" with pokemon_list=pokemon_list pokemon_images=pokemon_images pokemon_favourites=pokemon_favourites %}
{% endblock  %}

pokedexdjango/templates/pokedexdjango/top_10_hp.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<style>
h1 {
  text-align: center;
}
</style>
<h1 class="pokemon_list_header">
    TOP 10 Pokemon with the biggest health
</h1>
{% include "partials/pokemon_table.html" with pokemon_list=pokemon_list pokemon_images=pokemon_images pokemon_favourites=pokemon_favourites %}
{% endblock  %}

pokedexdjango/templates/pokedexdjango/top_10_not_legendary.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<style>
    h1{
    text-align: center;
    }
</style>
<h1 class="pokemon_list_header">
    TOP 10 Pokemons that are not legendary
</h1>
{% include "partials/pokemon_table.html" with pokemon_list=pokemon_list pokemon_images=pokemon_images pokemon_favourites=pokemon_favourites %}
{% endblock  %}

pokedexdjango/templates/pokedexdjango/top_10_pokemons.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<style>
h1 {
  text-align: center;
}
</style>
<h1 class="pokemon_list_header">
    TOP 10 Pokemons
</h1>
{% include "partials/pokemon_table.html" with pokemon_list=pokemon_list pokemon_images=pokemon_images pokemon_favourites=pokemon_favourites %}
{% endblock  %}

pokedexdjango/templates/pokedexdjango/top_10_water.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<style>
h1 {
  text-align: center;
}
</style>
<h1 class="pokemon_list_header">
    TOP 10 water Pokemon
</h1>
{% include "partials/pokemon_table.html" with pokemon_list=pokemon_list pokemon_images=pokemon_images pokemon_favourites=pokemon_favourites %}
{% endblock  %}

pokedexdjango/templates/pokedexdjango/user_info.html
{% extends 'base.html' %}


{% block content %}
<h1>User info page</h1>
{% if user.is_authenticated %}
<h2>Hi {{ user.username }}!</h2>
<div>Name: {{ user.first_name }}</div>
<div>Last name: {{ user.last_name }}</div>
<div>Email: {{ user.email }}</div>
<div>Last login: {{ user.last_login }}</div>
<div>
    <a href="{% url 'change_password' %}">Change password</a>
</div>
<div>
    <a href="{% url 'reset_password' %}">Reset password</a>
</div>
{% else %}
<p>You are not logged in</p>
<a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}