pokedexdjango/urls.py
from django.urls import path
from . import views

app_name = 'pokedexdjango'
urlpatterns = [
    path('', views.pokemon_list, name='home'),
    path('pokemon/list', views.pokemon_list, name='pokemon_list'),
    path('pokemon/details/<int:id>/', views.pokemon_details, name='pokemon_details'),
    path('pokemon/remove-favourite/<int:id>/', views.remove_fav_pokemon, name='remove_fav_pokemon'),
    path('pokemon/add-favourite/<int:id>/', views.add_fav_pokemon, name='add_fav_pokemon'),
    path('user_info/', views.user_info, name='user_info'),
    path('top_10/', views.top_10, name='top_10'),
    path('top_10_pokemons/', views.top_10_pokemons, name='top_10_pokemons'),
    path('top_10_not_legendary/', views.top_10_not_legendary, name='top_10_not_legendary'),
    path('top_10_water/', views.top_10_water, name='top_10_water'),
    path('top_10_attack/', views.top_10_attack, name='top_10_attack'),
    path('top_10_defence/', views.top_10_defence, name='top_10_defence'),
    path('top_10_hp/', views.top_10_hp, name='top_10_hp'),
    path("register/", views.register, name="register"),
    path("pokemon/list/favourite/", views.favourite_pokemons, name="favourite_pokemons"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
    # path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('', include('pokedexdjango.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path(
        'change_password/',
        auth_views.PasswordChangeView.as_view(
            template_name='registration/change_password.html',
            success_url='/'
        ),
        name='change_password'
    ),
    path(
        'reset_password/',
        auth_views.PasswordResetView.as_view(
            template_name='registration/reset_password.html',
            success_url='/'
        ),
        name='reset_password'
    ),

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
<!--    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"-->
<!--            integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"-->
<!--            crossorigin="anonymous"></script>-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>


    {% load static %}

    <link href="{% static 'css/main.css' %}?v=1" rel="stylesheet">
    <script src="{% static 'js/main.js' %}?v=1"></script>


    <!-- INSERT ADITIONAL INFORMATION TO THE HEAD TAG HERE-->
    {% block head %}
    {% endblock%}

    <!-- CHANGES THE PAGE TITLE IF THE VARIABLE "title" IS PASSED BY THE VIEW -->
    {% if title %}
    <title>{{title}}</title>
    {% else %}
    <!-- USE DEFAULT TITLE TEXT IF NO VARIABLE "title" IS PASSED BY THE VIEW -->
    <title>My Pokedexdjango App</title>
    {% endif %}

</head>
<body>
<!-- BOOTSTRAP NAVBAR CODE -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="d-flex justify-content-between px-5 mx-auto" style="width: 90%;">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link active" href="{% url 'pokedexdjango:pokemon_list' %}">Pokemon list</a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                   aria-expanded="false">
                    TOP 10
                </a>
                <ul class="dropdown-menu dropdown-menu-dark">
                    <li><a class="dropdown-item" href="{% url 'pokedexdjango:top_10_pokemons' %}">TOP 10 Pokemons</a></li>
                    <li><a class="dropdown-item" href="{% url 'pokedexdjango:top_10_not_legendary' %}">TOP 10 Pokemons that are not legendary</a></li>
                    <li><a class="dropdown-item" href="{% url 'pokedexdjango:top_10_water' %}">TOP 10 water Pokemons</a></li>
                    <li><a class="dropdown-item" href="{% url 'pokedexdjango:top_10_attack' %}">TOP 10 Pokemons with the best attack</a></li>
                    <li><a class="dropdown-item" href="{% url 'pokedexdjango:top_10_defence' %}">TOP 10 Pokemons with the best defence</a></li>
                    <li><a class="dropdown-item" href="{% url 'pokedexdjango:top_10_hp' %}">TOP 10 Pokemons with the biggest health</a></li>
                </ul>
            </li>

<!--            <li class="nav-item active">-->
<!--                <a class="nav-link active" href="{% url 'pokedexdjango:top_10' %}">TOP 10</a>-->
<!--            </li>-->
            {% if user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link active" href="{% url 'pokedexdjango:user_info' %}">User info</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link active" href="{% url 'pokedexdjango:favourite_pokemons' %}">Favourite pokemons</a>
            </li>
            {% else %}
            <li class="nav-item active">
                <a class="nav-link active" href="{% url 'pokedexdjango:register' %}">Register</a>
            </li>
            {% endif %}
        </ul>
        <span class="navbar-text text-white">
            {% if user.is_authenticated %}
<!--            <a class="nav-link active" href="{% url 'logout' %}">Logout</a>-->
            <a class="nav-link active" data-bs-toggle="modal" data-bs-target="#exampleModal">Logout</a>
            {% else %}
            <a class="nav-link active" href="{% url 'login' %}">Login</a>
            {% endif %}
        </span>
    </div>
</nav>
<!-- END OF NAVBAR CODE-->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <b class="modal-title fs-5" id="exampleModalLabel">Are you sure you want to log out?</b>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        This action will log you out.
      </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
            <a class="btn btn-primary" href="{% url 'logout' %}" role="button">Yes</a>
        </div>
    </div>
  </div>
</div>


<div class="container-fluid mt-5" style="max-width: 80%">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show  {% if message.tags == 'error' %} alert-danger {% endif %}"
         role="alert">
        {{ message }}

        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <!--        <button type="button" class="close" data-dismiss="alert">-->
        <!--            <span aria-hidden="true">&times;</span>-->
        <!--        </button>-->
    </div>
    {% endfor %}
    {% endif %}

    <!-- INSERT THE CONTENT FROM SPECIFIC PAGES HERE-->
    {% block content %}
    {% endblock %}
</div>


</body>
</html>